// Package state reads and writes .keel/state.json, the record of which
// modules keel init (and later keel add) selected for a generated
// project. Before this package existed, keel init left no trace of its
// own module selection anywhere in the generated output — keel add has
// nothing else to read to find out what's already present.
package state

import (
	"cmp"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
)

// SchemaVersion is the current .keel/state.json schema. Bump it and
// handle migration explicitly if the shape ever needs to change —
// the same posture module.yaml's own apiVersion field takes.
const SchemaVersion = 1

// RelPath is state.json's path relative to a project's root.
const RelPath = ".keel/state.json"

// ErrNotFound is returned by Load when projectDir has no
// .keel/state.json — keel add turns this into its own "this directory
// wasn't generated by keel init" message; it is not itself a generic
// I/O error.
var ErrNotFound = errors.New("state: no .keel/state.json found")

// Module records one resolved module's name and version. Deliberately
// nothing else — no content hash, no per-file record. Hashing would
// serve drift/upgrade detection, a different problem than keel add's
// actual need (knowing what's already selected, to compute a correct
// resolver.Resolve call); adding it now would be speculative scope for
// a problem nothing yet asks to solve.
type Module struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

// State is the decoded form of .keel/state.json.
type State struct {
	SchemaVersion int      `json:"schemaVersion"`
	Language      string   `json:"language"`
	Modules       []Module `json:"modules"`
}

// Load reads projectDir's .keel/state.json. Returns ErrNotFound if the
// file doesn't exist.
func Load(projectDir string) (*State, error) {
	data, err := os.ReadFile(filepath.Join(projectDir, filepath.FromSlash(RelPath)))
	if err != nil {
		if os.IsNotExist(err) {
			return nil, ErrNotFound
		}
		return nil, err
	}

	var s State
	if err := json.Unmarshal(data, &s); err != nil {
		return nil, fmt.Errorf("state: parsing %s: %w", RelPath, err)
	}
	return &s, nil
}

// Save writes s to projectDir/.keel/state.json, creating .keel/ if
// necessary. s.Modules is sorted by name before writing — the same
// determinism requirement as go.mod's dependency sort and
// .env.example's var sort: repeated Save calls on an equivalent module
// set must be byte-identical.
func Save(projectDir string, s *State) error {
	sorted := slices.Clone(s.Modules)
	slices.SortFunc(sorted, func(a, b Module) int { return cmp.Compare(a.Name, b.Name) })

	out := State{
		SchemaVersion: s.SchemaVersion,
		Language:      s.Language,
		Modules:       sorted,
	}

	data, err := json.MarshalIndent(&out, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')

	dir := filepath.Join(projectDir, filepath.Dir(filepath.FromSlash(RelPath)))
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	return os.WriteFile(filepath.Join(projectDir, filepath.FromSlash(RelPath)), data, 0o644) //nolint:gosec // state.json is ordinary project metadata, not sensitive
}

// Has reports whether s already lists a module named name.
func (s *State) Has(name string) bool {
	for _, m := range s.Modules {
		if m.Name == name {
			return true
		}
	}
	return false
}
