
package cli

import (
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"strings"

	"flag"

	keel "github.com/chibuike-kt/keel"
	"github.com/chibuike-kt/keel/internal/catalog"
	"github.com/chibuike-kt/keel/internal/renderer"
	"github.com/chibuike-kt/keel/internal/resolver"
	"github.com/chibuike-kt/keel/internal/state"
)

const addUsage = `Usage:
  keel add <module> [<module>...] [flags]

Flags:
`

const notKeelProjectMsg = "keel add: this directory wasn't generated by keel init — keel add requires a project created with keel init"

// cmdAdd is "keel add"'s real entry point: it loads keel's embedded
// module catalog and operates on the current working directory. See
// runAdd for the testable core this wraps.
func cmdAdd(args []string, out, errOut io.Writer) int {
	modulesFS, err := fs.Sub(keel.Modules, "modules")
	if err != nil {
		fmt.Fprintf(errOut, "keel add: %v\n", err)
		return 1
	}

	cat, err := catalog.LoadCatalog(modulesFS)
	if err != nil {
		fmt.Fprintf(errOut, "keel add: loading module catalog: %v\n", err)
		return 1
	}

	dir, err := os.Getwd()
	if err != nil {
		fmt.Fprintf(errOut, "keel add: %v\n", err)
		return 1
	}

	return runAdd(args, out, errOut, cat, keel.Modules, dir)
}

// runAdd implements "keel add", parameterized over its catalog,
// template filesystem, and target directory so it's testable against a
// synthetic catalog and a controlled project directory, without
// touching the real embedded module set or the process's real working
// directory.
func runAdd(args []string, out, errOut io.Writer, cat resolver.MapCatalog, templates fs.FS, targetDir string) int {
	flagSet := flag.NewFlagSet("add", flag.ContinueOnError)
	flagSet.SetOutput(errOut)
	dryRun := flagSet.Bool("dry-run", false, "show what would change without writing anything")
	force := flagSet.Bool("force", false, "overwrite files that already exist at a template's destination path")

	flagSet.Usage = func() {
		fmt.Fprint(errOut, addUsage)
		flagSet.PrintDefaults()
	}

	if len(args) > 0 && isAddHelpArg(args[0]) {
		flagSet.SetOutput(out)
		fmt.Fprint(out, addUsage)
		flagSet.PrintDefaults()
		return 0
	}

	if err := flagSet.Parse(args); err != nil {
		return 2
	}

	requested := dedupe(flagSet.Args())
	if len(requested) == 0 {
		fmt.Fprintln(errOut, "keel add: missing module name")
		flagSet.Usage()
		return 2
	}

	st, err := state.Load(targetDir)
	if err != nil {
		if errors.Is(err, state.ErrNotFound) {
			fmt.Fprintln(errOut, notKeelProjectMsg)
			return 1
		}
		fmt.Fprintf(errOut, "keel add: %v\n", err)
		return 1
	}

	var newRequested []string
	for _, name := range requested {
		if st.Has(name) {
			fmt.Fprintf(out, "%s is already in this project\n", name)
			continue
		}
		newRequested = append(newRequested, name)
	}
	if len(newRequested) == 0 {
		return 0
	}

	fullRequested := make([]string, 0, len(st.Modules)+len(newRequested))
	for _, m := range st.Modules {
		if m.Name == "base" {
			continue
		}
		fullRequested = append(fullRequested, m.Name)
	}
	fullRequested = append(fullRequested, newRequested...)

	plan, err := resolver.ResolveProject(cat, fullRequested, st.Language)
	if err != nil {
		printResolutionError(errOut, "keel add", err)
		return 1
	}

	ctx, err := renderer.ContextFromExisting(targetDir)
	if err != nil {
		fmt.Fprintf(errOut, "keel add: %v\n", err)
		return 1
	}

	r := renderer.New(templates)
	result, err := r.RenderAdd(plan, ctx, targetDir, st.Modules, renderer.AddOptions{Force: *force, DryRun: *dryRun})
	if err != nil {
		printAddError(errOut, err)
		return 1
	}

	printAddSuccess(out, result, *dryRun)
	return 0
}

// isAddHelpArg reports whether s is one of the conventional spellings
// of the help flag, checked against args[0] before flag parsing so
// "keel add -h" shows usage instead of being parsed as a module name.
func isAddHelpArg(s string) bool {
	return s == "-h" || s == "-help" || s == "--help"
}

// dedupe drops repeated entries from names while preserving first-seen
// order — so "keel add ledger ledger" behaves like "keel add ledger",
// not like a double request.
func dedupe(names []string) []string {
	seen := make(map[string]bool, len(names))
	out := make([]string, 0, len(names))
	for _, n := range names {
		if seen[n] {
			continue
		}
		seen[n] = true
		out = append(out, n)
	}
	return out
}

// printAddError reports RenderAdd's failure, aggregating every problem
// it found rather than just the first — the same posture printRenderError
// already takes for keel init.
func printAddError(errOut io.Writer, err error) {
	if addErr, ok := errors.AsType[*renderer.AddError](err); ok {
		fmt.Fprintln(errOut, "keel add: could not add the requested modules:")
		for _, problem := range addErr.Unwrap() {
			fmt.Fprintf(errOut, "  - %s\n", problem)
		}
		return
	}
	if renderErr, ok := errors.AsType[*renderer.RenderError](err); ok {
		fmt.Fprintln(errOut, "keel add: generation failed:")
		for _, problem := range renderErr.Unwrap() {
			fmt.Fprintf(errOut, "  - %s\n", problem)
		}
		return
	}
	fmt.Fprintf(errOut, "keel add: %v\n", err)
}

func printAddSuccess(out io.Writer, result *renderer.AddResult, dryRun bool) {
	names := make([]string, len(result.NewModules))
	for i, m := range result.NewModules {
		names[i] = m.Name
	}

	verb := "Added"
	if dryRun {
		verb = "Would add"
	}
	fmt.Fprintf(out, "%s modules: %s\n", verb, strings.Join(names, ", "))

	if len(result.Files) > 0 {
		fmt.Fprintf(out, "  files: %s\n", strings.Join(result.Files, ", "))
	}
	if len(result.GoModDeps) > 0 {
		fmt.Fprintf(out, "  go.mod dependencies: %s\n", strings.Join(result.GoModDeps, ", "))
	}
	if len(result.EnvVars) > 0 {
		fmt.Fprintf(out, "  .env.example vars: %s\n", strings.Join(result.EnvVars, ", "))
	}
}
